### ISSUE TITLE
off-by-one error in the bit range selection

### ISSUE THREAD

**Issue by elmiramou** [riscv/sail-riscv#1192]
@Alasdair Incorrect bit range in regval comparison ([32..16] instead of [31..16]) in line 40 in this path sail-cheri-riscv/sail-riscv/model/riscv_fdext_regs.sail

**Comment by pmundkur** [comment]
This seems to have been fixed in a2ffa8511f and improved even further via this refactor fae8e8b137b2d5. Closing as this issue does not apply to this repo.

**Comment by elmiramou** [comment]
it seems that it is still an issue in sail-cheri-riscv model, since it has not been updated ; https://github.com/riscv/sail-riscv/blob/b748a82361d12d20fa6da30d62b98a83ef8860d8/model/riscv_fdext_regs.sail

**Comment by nadime15** [comment]
Yes, but you will need to raise the issue here instead: https://github.com/CTSRD-CHERI/sail-cheri-riscv/issues

The CHERI RISC-V Sail model implements the CHERI extension, which is not supported by our Sail RISC-V Model. The two models are similar but still independent.

**Comment by Timmmm** [comment]
The `sail-cheri-riscv` repo is not really maintained any more and doesn't match the latest spec. The latest RISC-V CHERI code is the `codasip` branch here: https://github.com/CHERI-Alliance/sail-riscv

That is also about 4 months out of date but it includes this fix.

There are plans to update it to bring it up-to-date with the latest `master` branch but it will probably take a few months (it's going to be a hell of a rebase/merge). See https://github.com/CHERI-Alliance/sail-riscv/issues/1

**Comment by Alasdair** [comment]
My understanding is there are some plans to make CHERI an official extension? If that happens I think it would be better if the CHERI support was directly in this repository, perhaps in a `model/cheri` subdirectory.

**Comment by jrtc27** [comment]
> My understanding is there are some plans to make CHERI an official extension? If that happens I think it would be better if the CHERI support was directly in this repository, perhaps in a `model/cheri` subdirectory.

Yes, but catching up to the current master is step 1 of that.

**Comment by Timmmm** [comment]
Yeah that's exactly my plan - it's the final step of https://github.com/CHERI-Alliance/sail-riscv/issues/1

It's technically a new base architecture - like E - rather than an extension. It's getting the letter Y, so it will be RV32Y etc.
